askui/askui

docs/docs/general/02-Getting Started/writing-your-first-test.md, docs/docs/general/03-Best Practice/configure_test_framework.md, package-lock.json, packages/askui-nodejs/example_projects_templates/typescript_jest/test/jest.config.ts, packages/askui-nodejs/package.json
Added jest config for faster execution to example project jest.config.ts and documented it. Had to increase the major version of jest to be able to add the newest name of the config option to the example project (the name was changed between jest v27 and v28). Also added docu about the old option name.
=> AS-1061 fix slow jest

docs/docs/api/02-Commands/waitfor.md, packages/askui-nodejs/src/execution/dsl.ts, packages/askui-nodejs/src/execution/ui-control-client.ts
Follow-up:
- Adjust dsl template
- Remove `waits()` from ui controller
=> AS-1010 Fix waitFor()

.release-it.json, docs/docs/general/02-Getting Started/getting-started.md, docs/docs/general/03-Best Practice/configure_test_framework.md, docs/docs/general/06-Tutorials/shop-demo.md, docs/docs/general/06-Tutorials/spotify-tutorial.md, docs/package.json, examples/askui-nodejs-base-example/package.json, package-lock.json, package.json, packages/askui-nodejs/package.json
So that installation of dependency does not run into conflicts
=> Fix up Getting Started docs

docs/docs/general/07-Troubleshooting/ipv6.md, docs/docs/general/07-Troubleshooting/mac-os.md, packages/askui-nodejs/src/execution/ui-control-client.ts, packages/askui-nodejs/src/lib/ui-controller-darwin.ts
- name was not updated for mac
=> fix(askui-nodejs): connect to ui controller on mac

docs/versioned_docs/version-0.2.7/api/06-Configuration/askui-ui-control-client.md, docs/versioned_docs/version-0.2.7/general/02-Getting Started/getting-started.md, docs/versioned_docs/version-0.2.7/general/02-Getting Started/writing-your-first-test.md, docs/versioned_docs/version-0.2.7/general/07-Troubleshooting/index.md, docs/versioned_docs/version-0.3.1/api/06-Configuration/askui-ui-control-client.md, docs/versioned_docs/version-0.3.1/general/02-Getting Started/getting-started.md, docs/versioned_docs/version-0.3.1/general/02-Getting Started/writing-your-first-test.md, docs/versioned_docs/version-0.3.1/general/07-Troubleshooting/index.md, docs/versioned_docs/version-0.3.2/api/06-Configuration/askui-ui-control-client.md, docs/versioned_docs/version-0.3.2/general/02-Getting Started/getting-started.md, docs/versioned_docs/version-0.3.2/general/02-Getting Started/writing-your-first-test.md, docs/versioned_docs/version-0.3.2/general/07-Troubleshooting/index.md
In the previous PR the changes where only done in the next version of the docs.
I pulled them to 0.2.7, 0.3.1 and 0.3.2
=> Docs: Push changes from next to 0.2.7, 0.3.1 and 0.3.2

docs/docusaurus.config.js, docs/package.json, package-lock.json
* docusaurus upgrade
* Include UTM2Cookie script when in PROD mode
=> docs: upgrade to docusaurus 2.3.1; Include UTM2cookie script

packages/askui-nodejs/src/execution/ui-control-client.ts
Fix: type and typeIn secret text bug
=> fix(ui-control-client): fix type and typeIn secret text bug

packages/askui-nodejs/src/execution/inference-client.ts, packages/askui-nodejs/src/execution/model-composition-branch.ts, packages/askui-nodejs/src/execution/model-composition.ts, packages/askui-nodejs/src/execution/ui-control-client.ts, packages/askui-nodejs/src/execution/ui-controller-client-interface.ts
* Enable inference configuration through  the ui-controlclient configuration
**Jira**
CO-277
=> Enable model configuration (#CO-277)

docs/docs/general/03-Guides/extract-information.md, docs/versioned_docs/version-v0.10.1/general/03-Guides/extract-information.md
Add a short guide on how to use `get()` to extract information out of the UI.
=> docs: short guide for get()

packages/askui-nodejs/src/execution/dsl.ts
- accepted undefined instead of being optional
=> fix(packages/askui-nodejs): fix that text and index params are optional

docs/docs/api/08-Configuration/askui-ui-control-client.md, docs/spellchecker-dictionary, packages/askui-nodejs/src/core/reporting/instruction.ts, packages/askui-nodejs/src/execution/annotation-level.ts, packages/askui-nodejs/src/execution/index.ts, packages/askui-nodejs/src/execution/ui-control-client-dependency-builder.ts, packages/askui-nodejs/src/execution/ui-control-client.ts, packages/askui-nodejs/src/execution/ui-controller-client-interface.ts, packages/askui-nodejs/src/main.ts
- feat(packages/askui-nodejs)!: deprecate creating annotation file after instruc. (incl. config)
- fix(packages/askui-nodejs): fix auto-completion for reporter in UiControlClient's ClientArgs
=> deprecate annotation level

packages/askui-nodejs/src/utils/analytics/user-identifier.ts
=> fix: fix user identifier (#CO-411)

packages/askui-nodejs/src/core/model/annotation-result/detected-element.ts, packages/askui-nodejs/src/execution/dsl.ts
- add similarity score parameter to the withText filter
**Jira:** CO-444, CO-416
=> Askui-Lib: Make Fuzzy Matching score parameter available

docs/docs/api/09-Remote-Device-Controller.md, docs/versioned_docs/version-0.12.2/api/09-Remote-Device-Controller.md
@adi-wan-askui Please check if the comments from https://github.com/askui/askui/pull/564 got resolved.
=> docs: improvements for Remote Device Controller page

docs/docs/general/02-Getting Started/getting-started.md, docs/docs/general/02-Getting Started/guide-how-askui-works.md, docs/docs/general/02-Getting Started/write-your-first-instruction.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/getting-started.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/guide-how-askui-works.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/write-your-first-instruction.md
=> docs: remove link to app.askui.com (AskUI Studio) and replace it with link to signup form

docs/docs/api/08-Configuration/askui-ui-controller.md, docs/docs/api/09-Remote-Device-Controller.md, docs/docs/general/02-Getting Started/getting-started-linux.md, docs/docs/general/02-Getting Started/getting-started-macos.md, docs/docs/general/02-Getting Started/getting-started.md, docs/docs/general/05-Integrations/reporting.md, docs/docs/general/06-Tutorials/flutter-android-sample-app.md, docs/docs/general/06-Tutorials/google-cat-search.md, docs/docs/general/06-Tutorials/shop-demo.md, docs/docs/general/06-Tutorials/spotify-tutorial.md, docs/docs/general/07-Troubleshooting/ipv6.md, docs/docs/general/07-Troubleshooting/proxy.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/getting-started-linux.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/getting-started-macos.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/getting-started.md, docs/versioned_docs/version-0.12.2/general/02-Getting Started/write-your-first-instruction.md, docs/versioned_docs/version-0.12.2/general/05-Integrations/reporting.md, packages/askui-nodejs/src/lib/interactive_cli/create-example-project.ts
* Also reverted docs of `0.12.2` as there will be a new version `0.13.0`
=> docs: Adapt docs to actual state of interactive CLI

docs/blog/2024-01-15/2024-01-23.md, docs/docs/general/05-Integrations/SSO.md
- contains a list of identity providers and required information
- link to auth0 docs
- email contact to askui support team
=> SSO setup documentation + release notes

docs/docs/general/01-Getting Started/Installing AskUI/getting-started.md, docs/versioned_docs/version-0.13.1/general/01-Getting Started/Installing AskUI/getting-started.md, docs/versioned_docs/version-0.13.1/general/02-Components/AskUI-Runner.md
Hello,
I found a missing renaming.
=> Fix workspace id and token naming

packages/askui-nodejs/example_projects_templates/templates/askui-helper-windows.nj, packages/askui-nodejs/example_projects_templates/templates/askui-helper.nj, packages/askui-nodejs/src/execution/read-credentials.ts, packages/askui-nodejs/src/execution/read-environment-credentials.ts, packages/askui-nodejs/src/execution/ui-control-client-dependency-builder.ts, packages/askui-nodejs/src/lib/interactive_cli/cli-options-interface.ts, packages/askui-nodejs/src/lib/interactive_cli/cli.ts, packages/askui-nodejs/src/lib/interactive_cli/create-example-project.ts
- Include the `--skip-credentials` flag in the `askui init` command.
- Make sure credentials are defined before initiating the execution.
**Jira:** CO-620
=> Add skip Credentials Flag

packages/askui-nodejs/src/lib/interactive_cli/cli-options-interface.ts, packages/askui-nodejs/src/lib/interactive_cli/cli.ts, packages/askui-nodejs/src/lib/interactive_cli/create-example-project.ts
- Remove are you proxy user question from the cli.
=> Remove are you proxy user question

packages/askui-nodejs/src/core/reporting/step-reporter.ts, packages/askui-nodejs/src/execution/ui-controller-client.ts, packages/askui-nodejs/src/execution/ui-controller-not-connected-error.ts, packages/askui-nodejs/src/utils/http/custom-errors/index.ts, packages/askui-nodejs/src/utils/http/http-client-got.ts
- fix(askui-nodejs): log (not throw) error if reporter is misused to reveal underlying error (#CL-736)
- fix(askui-nodejs): fix retry of http requests, e.g., don't retry on user mistakes (#CL-736)
=> CL-736 Improve error handling

packages/askui-nodejs/src/core/ai-element/ai-element-collection.ts, packages/askui-nodejs/src/core/ai-element/ai-element-error.ts, packages/askui-nodejs/src/core/ai-element/ai-element.spec.ts, packages/askui-nodejs/src/core/ai-element/ai-element.ts, packages/askui-nodejs/src/execution/dsl.spec.ts, packages/askui-nodejs/src/execution/dsl.ts, packages/askui-nodejs/src/execution/ui-control-client-dependency-builder.ts, packages/askui-nodejs/src/execution/ui-control-client.ts, packages/askui-nodejs/src/utils/analytics/analytics.ts
- Add `aiElement` filter.
TODO: 
- Add documentation. 
**Jira:** CO-731
=> feat: Add AIElement Filter (#CO-731)

packages/askui-nodejs/src/core/ui-control-commands/action.ts, packages/askui-nodejs/src/core/ui-control-commands/control-command.ts, packages/askui-nodejs/src/execution/dsl.ts
- Allow parameters to be passed to actions.
- Introduce an optional parameter for the execOnShell command in the shell to specify the expected timeout.
**Jira:** CO-755
=> Add optional param to exec on shell command

CHANGELOG.md, packages/askui-nodejs/src/execution/ui-control-client.ts
@programminx-askui Do we need this docs also in `askui-inference`? And if so, where? I could not find the correct place.
=> docs: docs for ask() (#CL-897)

packages/askui-nodejs/src/execution/dsl.spec.ts, packages/askui-nodejs/src/execution/dsl.ts, packages/askui-nodejs/src/execution/execution-runtime.ts, packages/askui-nodejs/src/execution/inference-client.ts, packages/askui-nodejs/src/execution/ui-control-client.ts
Provide model composition for specific actions in exec() command. Model composition in Exec command will take precedence on the modelcomposition set inside `askui-helper.ts`.
=> feat(ML-595): add custom modelcomposition in exec
